#!/bin/sh

if [ -z "$1" ]; then
	echo "Need a packaging target."
	echo ""
	echo "$0 target [additional options]"
	echo ""
	exit 1
else
	package="$1"
fi

shift

SCRIPTDIR="$(dirname $0)"
"${SCRIPTDIR}/PackageScripts/${package}" "${SCRIPTDIR}" $@

