#!/bin/sh

if [ -z "$1" ]; then
	echo "Need a packaging target."
	echo ""
	echo "$0 target [additional options]"
	echo ""
	exit 1
else
	package="$1"
fi

shift

SCRIPTDIR="`( cd \"$(dirname \"$0\")\" && pwd )`"
if [ -z "$SCRIPTDIR" ] ; then
	echo "Unable to determine the location of $0"
	echo "Bailing out!"
	exit 44
fi

"${SCRIPTDIR}/PackageScripts/${package}" "${SCRIPTDIR}" $@

